### PR TITLE
Revert "Cache initial page"

### PR DESCRIPTION
**Pull request by hirasso**
Reverts swup/preload-plugin#29

Can we revert this? It needs another adjustment to work properly. `preloadPage` doesn't execute if the requested URL is the current URL: https://github.com/swup/preload-plugin/blob/master/src/index.js#L79

### CODE REVIEW

**Comment by hirasso** [comment]
Another thing I just noticed: `swup.getCurrentUrl()` only started existing very recently. In `v2.0.14`, wich I happened to have still installed in a test folder, it wasn't there already. So we should probably continue to use the direct import for `getCurrentUrl`. What do you think?

**Comment by daun** [comment]
I'd rather push a fix than reverting. One second...

**Comment by daun** [comment]
Agree about the helper.

**Comment by daun** [comment]
I opened #31 to fix these.

**Pull request closed without merging**
