### PR TITLE
Fix flaky tests

### PR DESCRIPTION
**Pull request by hirasso**
**Description**

Something is wrong with the CI:

- It [failed](https://github.com/swup/preload-plugin/actions/runs/10919079988/job/30305977270) when I merged the latest dependabot PR
- after I pulled the current master to my local machine, I _sometimes_ got an error for the test `allows for custom queue size`

I'm creating this PR just to test what's wrong.

**Checks**

- [x] The PR is submitted to the `master` branch

### CODE REVIEW

**Comment by hirasso** [comment]
...seems to be working alright... @daun, I can't make sense of the test that was failing:

https://github.com/swup/preload-plugin/blob/84b4418eb81fd079e255be7b8a0820dbadfa13d9/tests/unit/queue.test.ts#L59-L77

Would you like to explain what exactly it is testing? :)

**Comment by daun** [comment]
What‘s the error you‘re getting locally?

The particular test tries to confirm that the priority queue can have a custom length (i.e. preload max 5 links at once).

**Comment by hirasso** [comment]
CleanShot 2024-09-19 at 08 49 05@2x

Yesterday, `elapsed` also was was `104` instead of `106`, once

**Comment by daun** [comment]
Alright, so we‘ll need to add some slack around the number checks I guess?

**Comment by hirasso** [comment]
Yes! I think increasing the `padding` in `pad` could help. As I don't understand exactly how this is supposed to work, I'd be grateful if you would take care of it.

**Comment by daun** [comment]
Looking good now :)

**Review by daun — APPROVED** [review]

**Comment by hirasso** [comment]
👌

**Pull request merged**
