### PR TITLE
Move `@swup/plugin` from `dependencies` to `devDependencies`

### PR DESCRIPTION
**Pull request by hirasso**
Should prevent auto-installation of `node_modules` inside package after `npm i @swup/preload-plugin`, if I'm not mistaken. If this works, should also be fixed in scroll-plugin.

### CODE REVIEW

**Review by gmrchk — CHANGES_REQUESTED** [review]
It's a direct dependency, so unfortunatelly it can't be moved to devDeps currently. 
What we can do is move the CLI parts to the swup/cli, and that could be than installed as devDep in plugins for the build scripts.

**Comment by hirasso** [comment]
@gmrchk ok, apparently I'm still missing the full picture here. It'll probably easier if we discuss the problem and possible solution in person.

**Comment by daun** [comment]
It's definitely a normal dependency as we're including a method from that package.

@hirasso What's the issue with having a node_modules folder inside another package? That's how npm resolves different versions between packages. What we should do is not pin the plugin version but require a normal semver range.

**Comment by hirasso** [comment]
I should probably RTFM for `package.json` before creating PRs. Obviously I haven't yet fully understood NPMs dependencies concept, yet. Sorry for the noise 😅

**Comment by daun** [comment]
Haha, no worries!

**Comment by hirasso** [comment]
So, even after reading [through this](https://stackoverflow.com/a/22004559/586823) I don't understand why moving `@swup/plugin` to `devDependencies` would pose a problem. Looking forwrad to be enlightened by you guys in our next call 💡🙏

**Comment by daun** [comment]
Users of swup could have their production pipeline set up to not install dev dependencies via `--production`. In that case, none of the plugins that require the base class would have access to it since it won't be installed. It's not very common, but it's a possibility. Also, it's a direct dependency, not something only required while developing it like a linter or test runner.

**Pull request closed without merging**
