### PR TITLE
Minor version 1.1.0

### PR DESCRIPTION
**Pull request by hirasso**
- Introduces preloading links on `touchstart` (#41)
- Rejects for empty `page.blocks` just like swup does it

### CODE REVIEW

**Review by daun — APPROVED** [review]

**Comment by hirasso** [comment]
Sorry, forgot updated readme ::)

**Comment by hirasso** [comment]
Actually, the readme isn't complete yet. I still have to add an info about the new `touchstart` preload. But out of time for today, will convert the PR to a draft and request again if it's updated.

**Comment by hirasso** [comment]
@daun could you re-approve this? 💫

**Review by daun — APPROVED** [review]

**Comment by hirasso** [comment]
@daun I have updated the readme based on your comments. Ready for re-re-review 👾

**Review by daun — APPROVED** [review]

**Pull request merged**
