### PR TITLE
Fix package.json exports

### PR DESCRIPTION
**Pull request by hirasso**
**Description**

Fixes the package.json so that it points to the declaration files.

**Checks**

- [x] The PR is submitted to the `master` branch
- [x] The code was linted before pushing (`npm run lint`)

### CODE REVIEW

**Comment by daun** [comment]
After some research, this is probably the safest order of the exported members:

```json
  "exports": {
    ".": {
      "types": "./dist/index.d.ts",
      "import": "./dist/index.modern.js",
      "require": "./dist/index.cjs"
    }
  }
```

**Comment by hirasso** [comment]
Great, thanks for the research! I'll update it.

**Comment by hirasso** [comment]
Done

**Review by daun — APPROVED** [review]

**Comment by daun** [comment]
🏓

**Pull request merged**
